DB_HOST = "localhost"
DB_PORT = 3306
DB_NAME = "baixiu-dev"
DB_ACCOUNT = "root"
DB_PASSWORD = "123456"
MODULES_PATH = "modules"  # 视图函数路径
LOGIN_URL = "/adminLogin.html"  # 登录地址
LOGIN_COOKIE_NAME = "auth"  # seesion存放的key
ADMIN_INDEX = "/admin/index.html"